### ISSUE TITLE
can't edit on pingendo - nothing ap

### ISSUE THREAD

**Issue by Sacha96** [Planet-First-Alliance/www.planetfirstalliance.io#1]
<img width="1440" alt="Screenshot 2020-04-17 at 17 28 57" src="https://user-images.githubusercontent.com/54844940/79586063-ef9fc680-80d0-11ea-8f7b-5083c103e1be.png">

nothing appears apart from title and mission

**Comment by samaradel** [comment]
Pingendo can't identify it because it made with older libs than what Pingendo already uses.. so for this part please send the text and I gonna update it.
